/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.cacheblasters.fm.quest.definition'

export { $nsid }

/** A quest definition template. Servers define quests with objectives, prerequisites, and rewards. */
type Main = {
  $type: 'com.cacheblasters.fm.quest.definition'
  name: string
  description: string

  /**
   * Minimum level to accept this quest
   */
  level?: number

  /**
   * NPC definition ID that offers this quest
   */
  giver?: string

  /**
   * NPC definition ID to turn in quest (defaults to giver)
   */
  turnIn?: string

  /**
   * Quest definition IDs that must be completed first
   */
  prerequisites?: string[]

  /**
   * Ordered list of objectives to complete
   */
  objectives: Objective[]
  rewards?: Rewards

  /**
   * Whether this quest can be accepted again after completion
   */
  repeatable?: boolean
  tags?: string[]
}

export type { Main }

/** A quest definition template. Servers define quests with objectives, prerequisites, and rewards. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    name: l.string({ maxLength: 128 }),
    description: l.string({ maxLength: 4096 }),
    level: l.optional(l.integer({ minimum: 1 })),
    giver: l.optional(l.string()),
    turnIn: l.optional(l.string()),
    prerequisites: l.optional(l.array(l.string())),
    objectives: l.array(l.ref<Objective>((() => objective) as any)),
    rewards: l.optional(l.ref<Rewards>((() => rewards) as any)),
    repeatable: l.optional(l.boolean()),
    tags: l.optional(l.array(l.string())),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Objective = {
  $type?: 'com.cacheblasters.fm.quest.definition#objective'

  /**
   * Objective type
   */
  type: 'kill' | 'collect' | 'talk' | 'visit' | 'deliver' | l.UnknownString
  description: string

  /**
   * Target ID (NPC def ID, item def ID, or room ID)
   */
  target?: string

  /**
   * How many (default 1)
   */
  count?: number
}

export type { Objective }

const objective = l.typedObject<Objective>(
  $nsid,
  'objective',
  l.object({
    type: l.string<{
      knownValues: ['kill', 'collect', 'talk', 'visit', 'deliver']
    }>(),
    description: l.string({ maxLength: 256 }),
    target: l.optional(l.string()),
    count: l.optional(l.integer({ minimum: 1 })),
  }),
)

export { objective }

/** Rewards granted on quest completion */
type Rewards = {
  $type?: 'com.cacheblasters.fm.quest.definition#rewards'
  xp?: number
  gold?: number

  /**
   * Item definition IDs granted as rewards
   */
  items?: string[]
}

export type { Rewards }

/** Rewards granted on quest completion */
const rewards = l.typedObject<Rewards>(
  $nsid,
  'rewards',
  l.object({
    xp: l.optional(l.integer()),
    gold: l.optional(l.integer()),
    items: l.optional(l.array(l.string())),
  }),
)

export { rewards }
