/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.quest.progress";

export { $nsid };

/** A player's progress on a quest. Stored in the player's PDS and updated by the server. */
type Main = {
  $type: "com.cacheblasters.fm.quest.progress";

  /**
   * Quest definition ID
   */
  questId: string;

  /**
   * DID of the server that issued this quest
   */
  serverId: string;

  /**
   * Quest status
   */
  status: "active" | "completed" | "failed" | l.UnknownString;

  /**
   * Progress for each objective, parallel to quest definition objectives
   */
  objectives: ObjectiveProgress[];
  acceptedAt: l.DatetimeString;
  completedAt?: l.DatetimeString;
};

export type { Main };

/** A player's progress on a quest. Stored in the player's PDS and updated by the server. */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    questId: l.string(),
    serverId: l.string(),
    status: l.string<{ knownValues: ["active", "completed", "failed"] }>(),
    objectives: l.array(l.ref<ObjectiveProgress>((() => objectiveProgress) as any)),
    acceptedAt: l.string({ format: "datetime" }),
    completedAt: l.optional(l.string({ format: "datetime" })),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);

type ObjectiveProgress = {
  $type?: "com.cacheblasters.fm.quest.progress#objectiveProgress";
  current: number;
  required: number;
  done: boolean;
};

export type { ObjectiveProgress };

const objectiveProgress = l.typedObject<ObjectiveProgress>(
  $nsid,
  "objectiveProgress",
  l.object({ current: l.integer(), required: l.integer(), done: l.boolean() }),
);

export { objectiveProgress };
