/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.cacheblasters.fm.federation.registration'

export { $nsid }

/** Server registration record published to the AT Proto network for discovery by other federated servers */
type Main = {
  $type: 'com.cacheblasters.fm.federation.registration'

  /**
   * The server's AT Proto DID
   */
  serverDid: l.DidString

  /**
   * Human-readable server name
   */
  name: string

  /**
   * Server description
   */
  description?: string

  /**
   * WebSocket endpoint for gameplay connections
   */
  endpoint: l.UriString

  /**
   * XRPC endpoint for federation handshakes
   */
  xrpcEndpoint?: l.UriString

  /**
   * Recommended level range for this server
   */
  levelRange?: LevelRange

  /**
   * How this server handles incoming character data
   */
  trustPolicy?:
    | 'trust-all'
    | 'trust-listed'
    | 'trust-none'
    | 'trust-level-cap'
    | l.UnknownString

  /**
   * Number of outbound portals to other servers
   */
  portalCount?: number

  /**
   * Current number of connected players (updated periodically)
   */
  playerCount?: number
  createdAt: l.DatetimeString
  updatedAt?: l.DatetimeString
}

export type { Main }

/** Server registration record published to the AT Proto network for discovery by other federated servers */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    serverDid: l.string({ format: 'did' }),
    name: l.string({ maxLength: 128 }),
    description: l.optional(l.string({ maxLength: 4096 })),
    endpoint: l.string({ format: 'uri' }),
    xrpcEndpoint: l.optional(l.string({ format: 'uri' })),
    levelRange: l.optional(l.ref<LevelRange>((() => levelRange) as any)),
    trustPolicy: l.optional(
      l.string<{
        knownValues: [
          'trust-all',
          'trust-listed',
          'trust-none',
          'trust-level-cap',
        ]
      }>(),
    ),
    portalCount: l.optional(l.integer()),
    playerCount: l.optional(l.integer()),
    createdAt: l.string({ format: 'datetime' }),
    updatedAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type LevelRange = {
  $type?: 'com.cacheblasters.fm.federation.registration#levelRange'
  min?: number
  max?: number
}

export type { LevelRange }

const levelRange = l.typedObject<LevelRange>(
  $nsid,
  'levelRange',
  l.object({
    min: l.optional(l.integer({ minimum: 1 })),
    max: l.optional(l.integer({ minimum: 1 })),
  }),
)

export { levelRange }
