/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.cacheblasters.fm.federation.transfer'

export { $nsid }

/** Request character transfer from source to target server via portal traversal */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    token: l.string(),
    character: l.lexMap(),
    attestations: l.optional(l.lexMap()),
  }),
  l.jsonPayload({
    accepted: l.boolean(),
    sessionId: l.optional(l.string()),
    websocketUrl: l.optional(l.string({ format: 'uri' })),
    spawnRoom: l.optional(l.string()),
    serverName: l.optional(l.string()),
    reason: l.optional(l.string()),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
