/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.cacheblasters.fm.system.attribute'

export { $nsid }

/** Defines a character attribute that this server uses. Record key is the attribute ID (e.g. 'str', 'luck', 'sanity'). */
type Main = {
  $type: 'com.cacheblasters.fm.system.attribute'

  /**
   * Display name, e.g. 'Strength'
   */
  name: string
  description: string

  /**
   * Minimum value (default 1)
   */
  min?: number

  /**
   * Maximum value (default 999)
   */
  max?: number

  /**
   * Default value for new characters
   */
  defaultValue?: number

  /**
   * Grouping category, e.g. 'physical', 'mental', 'social'
   */
  category?: string
}

export type { Main }

/** Defines a character attribute that this server uses. Record key is the attribute ID (e.g. 'str', 'luck', 'sanity'). */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    name: l.string({ maxLength: 64 }),
    description: l.string({ maxLength: 512 }),
    min: l.optional(l.integer()),
    max: l.optional(l.integer()),
    defaultValue: l.optional(l.integer()),
    category: l.optional(l.string()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
