/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.system.class";

export { $nsid };

/** Defines a character class. Record key is the class ID (e.g. 'warrior', 'hacker'). */
type Main = {
  $type: "com.cacheblasters.fm.system.class";
  name: string;
  description: string;

  /**
   * Map of attribute ID -> base value, e.g. { 'str': 14, 'dex': 10 }
   */
  baseAttributes?: l.LexMap;

  /**
   * Map of attribute ID -> bonus value added to race/default base
   */
  attributeBonuses?: l.LexMap;

  /**
   * Spell IDs this class has access to
   */
  spells?: string[];

  /**
   * Descriptive tags, e.g. ['melee', 'tank'] or ['caster', 'healer']
   */
  tags?: string[];
};

export type { Main };

/** Defines a character class. Record key is the class ID (e.g. 'warrior', 'hacker'). */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    name: l.string({ maxLength: 64 }),
    description: l.string({ maxLength: 2048 }),
    baseAttributes: l.optional(l.lexMap()),
    attributeBonuses: l.optional(l.lexMap()),
    spells: l.optional(l.array(l.string())),
    tags: l.optional(l.array(l.string())),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
