/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.system.equipSlot";

export { $nsid };

/** Defines an equipment slot. Record key is the slot ID (e.g. 'mainHand', 'implant-cranial'). */
type Main = {
  $type: "com.cacheblasters.fm.system.equipSlot";
  name: string;
  description?: string;

  /**
   * Grouping, e.g. 'armor', 'weapon', 'accessory'
   */
  category?: string;

  /**
   * How many items can occupy this slot (default 1)
   */
  maxItems?: number;

  /**
   * Alternative names players can use to refer to this slot
   */
  aliases?: string[];
};

export type { Main };

/** Defines an equipment slot. Record key is the slot ID (e.g. 'mainHand', 'implant-cranial'). */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    name: l.string({ maxLength: 64 }),
    description: l.optional(l.string({ maxLength: 512 })),
    category: l.optional(l.string()),
    maxItems: l.optional(l.integer({ minimum: 1 })),
    aliases: l.optional(l.array(l.string())),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
