/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.system.formula";

export { $nsid };

/** Defines a derived stat formula. Record key is the derived stat ID (e.g. 'maxHp', 'maxMp', 'maxAp', 'carryWeight'). */
type Main = {
  $type: "com.cacheblasters.fm.system.formula";
  name: string;
  description?: string;

  /**
   * Formula expression. Variables: 'level', any attribute ID (e.g. 'str', 'con'), and constants. Example: '20 + (level - 1) * 8 + con / 2'
   */
  expression: string;

  /**
   * Minimum result value
   */
  min?: number;

  /**
   * Maximum result value
   */
  max?: number;
};

export type { Main };

/** Defines a derived stat formula. Record key is the derived stat ID (e.g. 'maxHp', 'maxMp', 'maxAp', 'carryWeight'). */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    name: l.string({ maxLength: 64 }),
    description: l.optional(l.string({ maxLength: 512 })),
    expression: l.string({ maxLength: 1024 }),
    min: l.optional(l.integer()),
    max: l.optional(l.integer()),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
