/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.system.itemType";

export { $nsid };

/** Defines an item type and what properties items of this type can have. Record key is the type ID (e.g. 'weapon', 'implant', 'potion'). */
type Main = {
  $type: "com.cacheblasters.fm.system.itemType";
  name: string;
  description?: string;

  /**
   * Properties that items of this type can have
   */
  properties?: PropertyDef[];
  stackable?: boolean;
  equippable?: boolean;

  /**
   * Which equipment slot IDs this type can go in
   */
  equipSlots?: string[];

  /**
   * Default slot ID if not specified on the item
   */
  defaultSlot?: string;
};

export type { Main };

/** Defines an item type and what properties items of this type can have. Record key is the type ID (e.g. 'weapon', 'implant', 'potion'). */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    name: l.string({ maxLength: 64 }),
    description: l.optional(l.string({ maxLength: 512 })),
    properties: l.optional(l.array(l.ref<PropertyDef>((() => propertyDef) as any))),
    stackable: l.optional(l.boolean()),
    equippable: l.optional(l.boolean()),
    equipSlots: l.optional(l.array(l.string())),
    defaultSlot: l.optional(l.string()),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);

type PropertyDef = {
  $type?: "com.cacheblasters.fm.system.itemType#propertyDef";
  id: string;
  name: string;
  valueType: "integer" | "number" | "string" | "boolean" | l.UnknownString;
  description?: string;
};

export type { PropertyDef };

const propertyDef = l.typedObject<PropertyDef>(
  $nsid,
  "propertyDef",
  l.object({
    id: l.string(),
    name: l.string({ maxLength: 64 }),
    valueType: l.string<{
      knownValues: ["integer", "number", "string", "boolean"];
    }>(),
    description: l.optional(l.string({ maxLength: 256 })),
  }),
);

export { propertyDef };
