/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.system.race";

export { $nsid };

/** Defines a character race/species. Record key is the race ID. */
type Main = {
  $type: "com.cacheblasters.fm.system.race";
  name: string;
  description: string;

  /**
   * Map of attribute ID -> bonus value, e.g. { 'str': 2, 'con': 1 }
   */
  attributeBonuses?: l.LexMap;
  tags?: string[];
};

export type { Main };

/** Defines a character race/species. Record key is the race ID. */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    name: l.string({ maxLength: 64 }),
    description: l.string({ maxLength: 2048 }),
    attributeBonuses: l.optional(l.lexMap()),
    tags: l.optional(l.array(l.string())),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
