/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.cacheblasters.fm.system.spell'

export { $nsid }

/** Defines a spell. Record key is the spell ID (e.g. 'fireball', 'heal'). */
type Main = {
  $type: 'com.cacheblasters.fm.system.spell'
  name: string
  description: string
  mpCost: number

  /**
   * Action point cost (defaults to 2 if unset)
   */
  apCost?: number
  levelRequired?: number

  /**
   * Attribute ID used for spell power scaling (e.g. 'int', 'wis')
   */
  attribute: string
  effect: 'damage' | 'heal' | 'buff' | 'debuff' | l.UnknownString

  /**
   * Base power before attribute scaling
   */
  power: number

  /**
   * Dice notation for variable component, e.g. '2d6'
   */
  dice?: string
  target: 'enemy' | 'self' | 'ally' | l.UnknownString
  tags?: string[]
}

export type { Main }

/** Defines a spell. Record key is the spell ID (e.g. 'fireball', 'heal'). */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    name: l.string({ maxLength: 64 }),
    description: l.string({ maxLength: 2048 }),
    mpCost: l.integer({ minimum: 0 }),
    apCost: l.optional(l.integer({ minimum: 0 })),
    levelRequired: l.optional(l.integer({ minimum: 1 })),
    attribute: l.string(),
    effect: l.string<{ knownValues: ['damage', 'heal', 'buff', 'debuff'] }>(),
    power: l.integer(),
    dice: l.optional(l.string()),
    target: l.string<{ knownValues: ['enemy', 'self', 'ally'] }>(),
    tags: l.optional(l.array(l.string())),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
