/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.character.profile";

export { $nsid };

/** A player's character profile in Federated Realms. Attributes are an open map — each server defines what attributes it uses via system.attribute records. */
type Main = {
  $type: "com.cacheblasters.fm.character.profile";
  name: string;

  /**
   * Class ID referencing the originating server's system.class definition
   */
  class: string;

  /**
   * Race ID referencing the originating server's system.race definition
   */
  race: string;
  level: number;
  experience: number;

  /**
   * Open map of attribute ID -> numeric value, e.g. { 'str': 14, 'dex': 12, 'sanity': 80 }. Attribute IDs reference system.attribute definitions.
   */
  attributes: l.LexMap;

  /**
   * Cached derived stats computed from formulas, e.g. { 'maxHp': 50, 'maxMp': 30 }. Recomputed by each server using its own formulas.
   */
  derived?: l.LexMap;
  description?: string;

  /**
   * DID of the server where this character was created. Used to resolve class/race/attribute definitions.
   */
  homeServer?: l.DidString;

  /**
   * Server-specific extension data, keyed by server DID. Preserved across transfers even if the destination server doesn't understand it.
   */
  extensions?: l.LexMap;
  createdAt: l.DatetimeString;
  updatedAt?: l.DatetimeString;
};

export type { Main };

/** A player's character profile in Federated Realms. Attributes are an open map — each server defines what attributes it uses via system.attribute records. */
const main = l.record<"literal:self", Main>(
  "literal:self",
  $nsid,
  l.object({
    name: l.string({ maxLength: 64 }),
    class: l.string(),
    race: l.string(),
    level: l.integer({ minimum: 1, maximum: 9999 }),
    experience: l.integer({ minimum: 0 }),
    attributes: l.lexMap(),
    derived: l.optional(l.lexMap()),
    description: l.optional(l.string({ maxLength: 2048 })),
    homeServer: l.optional(l.string({ format: "did" })),
    extensions: l.optional(l.lexMap()),
    createdAt: l.string({ format: "datetime" }),
    updatedAt: l.optional(l.string({ format: "datetime" })),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
