/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.item.definition";

export { $nsid };

/** An item definition template. Properties are open — servers define what properties items have via system.itemType records. */
type Main = {
  $type: "com.cacheblasters.fm.item.definition";
  name: string;

  /**
   * Item type ID referencing server's system.itemType definition
   */
  type: string;
  description: string;
  weight?: number;
  value?: number;
  rarity?: string;
  levelRequired?: number;
  stackable?: boolean;
  maxStack?: number;

  /**
   * Open map of property ID -> value, defined by the item's type schema
   */
  properties?: l.LexMap;
  tags?: string[];
};

export type { Main };

/** An item definition template. Properties are open — servers define what properties items have via system.itemType records. */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    name: l.string({ maxLength: 128 }),
    type: l.string(),
    description: l.string({ maxLength: 4096 }),
    weight: l.optional(l.integer()),
    value: l.optional(l.integer()),
    rarity: l.optional(l.string()),
    levelRequired: l.optional(l.integer({ minimum: 1 })),
    stackable: l.optional(l.boolean()),
    maxStack: l.optional(l.integer()),
    properties: l.optional(l.lexMap()),
    tags: l.optional(l.array(l.string())),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
