/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.craft.recipe";

export { $nsid };

/** A crafting recipe defining ingredients, station requirement, and output. */
type Main = {
  $type: "com.cacheblasters.fm.craft.recipe";
  name: string;
  description?: string;

  /**
   * Required crafting station type (e.g. 'campfire', 'forge', 'alchemy'). Omit for hand-crafting.
   */
  station?: string;
  levelRequired?: number;
  ingredients: Ingredient[];
  output: Output;

  /**
   * Base success percentage. Defaults to 100 if omitted.
   */
  successChance?: number;
  tags?: string[];
};

export type { Main };

/** A crafting recipe defining ingredients, station requirement, and output. */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    name: l.string({ maxLength: 128 }),
    description: l.optional(l.string({ maxLength: 1024 })),
    station: l.optional(l.string()),
    levelRequired: l.optional(l.integer({ minimum: 1 })),
    ingredients: l.array(l.ref<Ingredient>((() => ingredient) as any), {
      maxLength: 10,
    }),
    output: l.ref<Output>((() => output) as any),
    successChance: l.optional(l.integer({ minimum: 1, maximum: 100 })),
    tags: l.optional(l.array(l.string())),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);

type Ingredient = {
  $type?: "com.cacheblasters.fm.craft.recipe#ingredient";

  /**
   * Item definition ID
   */
  itemId: string;
  count: number;
};

export type { Ingredient };

const ingredient = l.typedObject<Ingredient>(
  $nsid,
  "ingredient",
  l.object({ itemId: l.string(), count: l.integer({ minimum: 1 }) }),
);

export { ingredient };

type Output = {
  $type?: "com.cacheblasters.fm.craft.recipe#output";

  /**
   * Item definition ID for the crafted result
   */
  itemId: string;
  count: number;
};

export type { Output };

const output = l.typedObject<Output>(
  $nsid,
  "output",
  l.object({ itemId: l.string(), count: l.integer({ minimum: 1 }) }),
);

export { output };
