#!/usr/bin/env bash
# bootstrap-pds.sh — Set up a local PDS + dungeon server for development
#
# Usage:
#   ./scripts/bootstrap-pds.sh              # Interactive setup
#   ./scripts/bootstrap-pds.sh --defaults   # Use all defaults (localhost dev)
#
# What it does:
#   1. Generates secrets (PDS JWT secret, admin password, server password)
#   2. Creates .env from .env.example + AT Proto config
#   3. Starts the PDS container
#   4. Waits for PDS health
#   5. Creates the server account on the PDS
#   6. Writes SERVER_DID back into .env
#   7. Optionally creates a test player account

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
COMPOSE_FILE="$REPO_ROOT/docker-compose.yml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
err()   { echo -e "${RED}[err]${NC}   $*" >&2; }

# ── Pre-flight checks ──

command -v docker >/dev/null 2>&1 || { err "docker is required but not installed."; exit 1; }
docker info >/dev/null 2>&1 || { err "Docker daemon is not running."; exit 1; }

# ── Determine mode ──

USE_DEFAULTS=false
if [[ "${1:-}" == "--defaults" ]]; then
  USE_DEFAULTS=true
fi

# ── Generate secrets ──

generate_secret() {
  openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64
}

# ── Prompt or use default ──

prompt_or_default() {
  local var_name="$1"
  local prompt_text="$2"
  local default_val="$3"

  if [[ "$USE_DEFAULTS" == true ]]; then
    echo "$default_val"
    return
  fi

  read -rp "$(echo -e "${CYAN}?${NC} ${prompt_text} [${default_val}]: ")" input
  echo "${input:-$default_val}"
}

# ── Check for existing .env ──

if [[ -f "$ENV_FILE" ]]; then
  if [[ "$USE_DEFAULTS" == true ]]; then
    warn ".env already exists — overwriting (--defaults mode)"
  else
    echo ""
    warn ".env already exists."
    read -rp "$(echo -e "${YELLOW}?${NC} Overwrite? (y/N): ")" overwrite
    if [[ "$(echo "$overwrite" | tr '[:upper:]' '[:lower:]')" != "y" ]]; then
      info "Keeping existing .env. To start fresh, delete it first."
      exit 0
    fi
  fi
fi

echo ""
echo -e "${CYAN}╔══════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   Federated Realms — PDS Bootstrap   ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════╝${NC}"
echo ""

# ── Gather configuration ──

PDS_HOSTNAME=$(prompt_or_default "PDS_HOSTNAME" "PDS hostname (for handles)" "localhost")
PDS_PORT=$(prompt_or_default "PDS_PORT" "PDS external port" "2583")
SERVER_PORT=$(prompt_or_default "PORT" "Game server port" "3000")
SERVER_NAME=$(prompt_or_default "SERVER_NAME" "Server name" "Federated Realms")
SERVER_DESCRIPTION=$(prompt_or_default "SERVER_DESCRIPTION" "Server description" "A mysterious dungeon awaits...")
# PDS uses .test domain when hostname is localhost
if [[ "$PDS_HOSTNAME" == "localhost" ]]; then
  DEFAULT_HANDLE="dungeon-server.test"
else
  DEFAULT_HANDLE="server.${PDS_HOSTNAME}"
fi
SERVER_HANDLE=$(prompt_or_default "SERVER_HANDLE" "Server AT Proto handle" "$DEFAULT_HANDLE")
DEFAULT_SPAWN=$(prompt_or_default "DEFAULT_SPAWN" "Default spawn room" "starter-town:town-square")

# Determine public URL
if [[ "$PDS_HOSTNAME" == "localhost" ]]; then
  DEFAULT_PUBLIC_URL="http://localhost:${SERVER_PORT}"
else
  DEFAULT_PUBLIC_URL="https://${PDS_HOSTNAME}"
fi
PUBLIC_URL=$(prompt_or_default "PUBLIC_URL" "Public URL (for OAuth callbacks)" "$DEFAULT_PUBLIC_URL")

# Trust policy
TRUST_POLICY=$(prompt_or_default "TRUST_POLICY" "Federation trust policy (trust-all/trust-listed/trust-none/trust-level-cap)" "trust-all")

# Generate secrets
info "Generating secrets..."
PDS_JWT_SECRET=$(generate_secret)
PDS_ADMIN_PASSWORD=$(generate_secret)
SERVER_PASSWORD=$(generate_secret)
PDS_ROTATION_KEY=$(openssl ecparam -name secp256k1 -genkey -noout 2>/dev/null | openssl ec -outform DER 2>/dev/null | tail -c 32 | xxd -p -c 32 2>/dev/null || openssl rand -hex 32)

ok "Secrets generated"

# Compute PDS_URL
if [[ "$PDS_HOSTNAME" == "localhost" ]]; then
  PDS_URL="http://localhost:${PDS_PORT}"
else
  PDS_URL="https://${PDS_HOSTNAME}"
fi

# ── Write .env ──

cat > "$ENV_FILE" << EOF
# ──────────────────────────────────────
# Federated Realms — Generated by bootstrap-pds.sh
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ──────────────────────────────────────

# Server
PORT=${SERVER_PORT}
SERVER_NAME=${SERVER_NAME}
SERVER_DESCRIPTION=${SERVER_DESCRIPTION}
DEFAULT_SPAWN=${DEFAULT_SPAWN}

# PDS (Personal Data Server)
PDS_HOSTNAME=${PDS_HOSTNAME}
PDS_PORT=${PDS_PORT}
PDS_JWT_SECRET=${PDS_JWT_SECRET}
PDS_ADMIN_PASSWORD=${PDS_ADMIN_PASSWORD}
PDS_ROTATION_KEY=${PDS_ROTATION_KEY}

# PDS Email (required by PDS, use dummy values for local dev)
PDS_EMAIL_SMTP_URL=smtp://fake:25
PDS_EMAIL_FROM_ADDRESS=noreply@${PDS_HOSTNAME}

# AT Proto — Server Identity
PDS_URL=${PDS_URL}
SERVER_HANDLE=${SERVER_HANDLE}
SERVER_PASSWORD=${SERVER_PASSWORD}
SERVER_DID=
PUBLIC_URL=${PUBLIC_URL}

# Federation
TRUST_POLICY=${TRUST_POLICY}
TRUSTED_SERVERS=
MAX_ACCEPTED_LEVEL=50

# Bluesky Bridge (optional)
BSKY_ENABLED=false
BSKY_IDENTIFIER=
BSKY_PASSWORD=
BSKY_SERVICE=https://bsky.social
BSKY_POST_TYPES=chat,shout,event
BSKY_PLAYER_CROSSPOST=true
BSKY_THREAD_REFRESH=60
BSKY_THROTTLE_MS=2000
EOF

ok "Wrote .env"

# ── Start PDS ──

info "Starting PDS container..."
docker compose -f "$COMPOSE_FILE" up -d pds 2>&1

# Wait for PDS health
PDS_INTERNAL_URL="http://localhost:${PDS_PORT}"
info "Waiting for PDS to become healthy at ${PDS_INTERNAL_URL}..."

MAX_WAIT=60
WAITED=0
while ! curl -sf "${PDS_INTERNAL_URL}/xrpc/_health" >/dev/null 2>&1; do
  sleep 2
  WAITED=$((WAITED + 2))
  if [[ $WAITED -ge $MAX_WAIT ]]; then
    err "PDS did not become healthy after ${MAX_WAIT}s"
    err "Check: docker compose logs pds"
    exit 1
  fi
  printf "."
done
echo ""
ok "PDS is healthy"

# ── Create server account ──

info "Creating server account: ${SERVER_HANDLE}"

# Create account via PDS API
CREATE_RESPONSE=$(curl -s -X POST "${PDS_INTERNAL_URL}/xrpc/com.atproto.server.createAccount" \
  -H "Content-Type: application/json" \
  -d "{
    \"handle\": \"${SERVER_HANDLE}\",
    \"email\": \"server@example.com\",
    \"password\": \"${SERVER_PASSWORD}\"
  }" 2>&1)

# Check if account creation failed
if echo "$CREATE_RESPONSE" | grep -q '"error"'; then
  # Check if it's a "handle taken" error (server was already bootstrapped)
  if echo "$CREATE_RESPONSE" | grep -qi "handle.*taken\|already.*taken\|HandleNotAvailable"; then
    warn "Server account already exists — logging in to retrieve DID..."
    LOGIN_RESPONSE=$(curl -s -X POST "${PDS_INTERNAL_URL}/xrpc/com.atproto.server.createSession" \
      -H "Content-Type: application/json" \
      -d "{
        \"identifier\": \"${SERVER_HANDLE}\",
        \"password\": \"${SERVER_PASSWORD}\"
      }")
    SERVER_DID=$(echo "$LOGIN_RESPONSE" | grep -o '"did":"[^"]*"' | head -1 | cut -d'"' -f4)
  else
    err "Failed to create server account:"
    echo "$CREATE_RESPONSE"
    err "The PDS may require invite codes or have other restrictions."
    err "You can try creating the account manually and setting SERVER_DID in .env"
    exit 1
  fi
fi

# Extract DID from creation response if we haven't already
if [[ -z "${SERVER_DID:-}" ]]; then
  SERVER_DID=$(echo "$CREATE_RESPONSE" | grep -o '"did":"[^"]*"' | head -1 | cut -d'"' -f4)
fi

if [[ -z "$SERVER_DID" ]]; then
  err "Could not extract server DID from response"
  exit 1
fi

ok "Server DID: ${SERVER_DID}"

# Write SERVER_DID back into .env
sed -i.bak "s/^SERVER_DID=$/SERVER_DID=${SERVER_DID}/" "$ENV_FILE" && rm -f "${ENV_FILE}.bak"
ok "Updated .env with SERVER_DID"

# ── Optionally create a test player account ──

CREATE_PLAYER=false
if [[ "$USE_DEFAULTS" == true ]]; then
  CREATE_PLAYER=true
else
  echo ""
  read -rp "$(echo -e "${CYAN}?${NC} Create a test player account? (Y/n): ")" create_player_input
  if [[ "$(echo "$create_player_input" | tr '[:upper:]' '[:lower:]')" != "n" ]]; then
    CREATE_PLAYER=true
  fi
fi

if [[ "$CREATE_PLAYER" == true ]]; then
  if [[ "$PDS_HOSTNAME" == "localhost" ]]; then
    DEFAULT_PLAYER_HANDLE="testplayer.test"
  else
    DEFAULT_PLAYER_HANDLE="testplayer.${PDS_HOSTNAME}"
  fi
  PLAYER_HANDLE=$(prompt_or_default "PLAYER_HANDLE" "Test player handle" "$DEFAULT_PLAYER_HANDLE")
  PLAYER_PASSWORD=$(prompt_or_default "PLAYER_PASSWORD" "Test player password" "password")
  PLAYER_EMAIL=$(prompt_or_default "PLAYER_EMAIL" "Test player email" "test@example.com")

  info "Creating test player: ${PLAYER_HANDLE}"

  PLAYER_RESPONSE=$(curl -sf -X POST "${PDS_INTERNAL_URL}/xrpc/com.atproto.server.createAccount" \
    -H "Content-Type: application/json" \
    -d "{
      \"handle\": \"${PLAYER_HANDLE}\",
      \"email\": \"${PLAYER_EMAIL}\",
      \"password\": \"${PLAYER_PASSWORD}\"
    }" 2>&1) || {
    if echo "$PLAYER_RESPONSE" | grep -qi "handle.*taken\|already.*taken"; then
      warn "Test player account already exists — skipping"
    else
      warn "Failed to create test player: ${PLAYER_RESPONSE}"
    fi
  }

  PLAYER_DID=$(echo "${PLAYER_RESPONSE:-}" | grep -o '"did":"[^"]*"' | head -1 | cut -d'"' -f4 || true)
  if [[ -n "$PLAYER_DID" ]]; then
    ok "Test player DID: ${PLAYER_DID}"
  fi
fi

# ── Summary ──

echo ""
echo -e "${GREEN}╔══════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         Bootstrap complete!          ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════╝${NC}"
echo ""
echo -e "  PDS URL:        ${CYAN}${PDS_INTERNAL_URL}${NC}"
echo -e "  Server DID:     ${CYAN}${SERVER_DID}${NC}"
echo -e "  Server Handle:  ${CYAN}${SERVER_HANDLE}${NC}"
echo -e "  Public URL:     ${CYAN}${PUBLIC_URL}${NC}"
echo -e "  Trust Policy:   ${CYAN}${TRUST_POLICY}${NC}"
echo ""
echo -e "  ${YELLOW}Next steps:${NC}"
echo -e "    1. Start the dungeon server:"
echo -e "       ${CYAN}cd apps/dungeon-server && bun run src/index.ts${NC}"
echo -e "    2. Or start everything with Docker:"
echo -e "       ${CYAN}docker compose up${NC}"
echo -e "    3. Connect with the CLI client:"
echo -e "       ${CYAN}cd apps/cli-client && bun run src/index.tsx${NC}"
if [[ "$CREATE_PLAYER" == true && -n "${PLAYER_DID:-}" ]]; then
  echo ""
  echo -e "  ${YELLOW}Test player:${NC}"
  echo -e "    Handle:   ${CYAN}${PLAYER_HANDLE}${NC}"
  echo -e "    Password: ${CYAN}${PLAYER_PASSWORD}${NC}"
  echo -e "    DID:      ${CYAN}${PLAYER_DID}${NC}"
fi
echo ""
