/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.world.area";

export { $nsid };

/** An area grouping rooms in a dungeon server */
type Main = {
  $type: "com.cacheblasters.fm.world.area";
  title: string;
  description: string;
  levelRange?: LevelRange;
};

export type { Main };

/** An area grouping rooms in a dungeon server */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    title: l.string({ maxLength: 128 }),
    description: l.string({ maxLength: 4096 }),
    levelRange: l.optional(l.ref<LevelRange>((() => levelRange) as any)),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);

type LevelRange = {
  $type?: "com.cacheblasters.fm.world.area#levelRange";
  min?: number;
  max?: number;
};

export type { LevelRange };

const levelRange = l.typedObject<LevelRange>(
  $nsid,
  "levelRange",
  l.object({ min: l.optional(l.integer()), max: l.optional(l.integer()) }),
);

export { levelRange };
