/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.world.flag";

export { $nsid };

/** Definition of a room flag. Servers publish these to describe custom flags they support. */
type Main = {
  $type: "com.cacheblasters.fm.world.flag";
  name: string;
  description: string;
  effects?: FlagEffect[];
};

export type { Main };

/** Definition of a room flag. Servers publish these to describe custom flags they support. */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    name: l.string({ maxLength: 64 }),
    description: l.string({ maxLength: 1024 }),
    effects: l.optional(l.array(l.ref<FlagEffect>((() => flagEffect) as any), { maxLength: 10 })),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);

type FlagEffect = {
  $type?: "com.cacheblasters.fm.world.flag#flagEffect";

  /**
   * The effect type, e.g. 'disable-combat', 'disable-magic', 'damage-over-time', 'heal-over-time', 'movement-penalty'
   */
  type: string;
  value?: number;
  description?: string;
};

export type { FlagEffect };

const flagEffect = l.typedObject<FlagEffect>(
  $nsid,
  "flagEffect",
  l.object({
    type: l.string(),
    value: l.optional(l.integer()),
    description: l.optional(l.string({ maxLength: 256 })),
  }),
);

export { flagEffect };
