/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.world.portal";

export { $nsid };

/** A portal connecting this server to a room on another federated server. Published for discovery so other servers and clients can see the network topology. */
type Main = {
  $type: "com.cacheblasters.fm.world.portal";

  /**
   * Room ID on this server where the portal is located
   */
  sourceRoom: string;

  /**
   * Direction of the portal exit in the source room
   */
  direction:
    | "north"
    | "south"
    | "east"
    | "west"
    | "up"
    | "down"
    | "northeast"
    | "northwest"
    | "southeast"
    | "southwest"
    | l.UnknownString;

  /**
   * DID of the destination server
   */
  targetServerDid: l.DidString;

  /**
   * Room ID on the destination server
   */
  targetRoom: string;

  /**
   * In-game description of the portal
   */
  description?: string;

  /**
   * Minimum level required to use this portal
   */
  requiredLevel?: number;

  /**
   * Whether the target server has a corresponding portal back
   */
  bidirectional?: boolean;
};

export type { Main };

/** A portal connecting this server to a room on another federated server. Published for discovery so other servers and clients can see the network topology. */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    sourceRoom: l.string(),
    direction: l.string<{
      knownValues: [
        "north",
        "south",
        "east",
        "west",
        "up",
        "down",
        "northeast",
        "northwest",
        "southeast",
        "southwest",
      ];
    }>(),
    targetServerDid: l.string({ format: "did" }),
    targetRoom: l.string(),
    description: l.optional(l.string({ maxLength: 512 })),
    requiredLevel: l.optional(l.integer({ minimum: 1 })),
    bidirectional: l.optional(l.boolean()),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
