/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.world.room";

export { $nsid };

/** A room in the game world */
type Main = {
  $type: "com.cacheblasters.fm.world.room";
  title: string;
  description: string;
  area: string;
  coordinates: Coordinates;
  exits?: Exit[];

  /**
   * Room flags. Base conventions: safe, pvp, no-magic, dark, underwater, no-recall. Servers can define custom flags via com.cacheblasters.fm.world.flag records.
   */
  flags?: string[];
};

export type { Main };

/** A room in the game world */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    title: l.string({ maxLength: 256 }),
    description: l.string({ maxLength: 8192 }),
    area: l.string(),
    coordinates: l.ref<Coordinates>((() => coordinates) as any),
    exits: l.optional(l.array(l.ref<Exit>((() => exit) as any), { maxLength: 12 })),
    flags: l.optional(l.array(l.string())),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);

type Coordinates = {
  $type?: "com.cacheblasters.fm.world.room#coordinates";
  x: number;
  y: number;
  z: number;
};

export type { Coordinates };

const coordinates = l.typedObject<Coordinates>(
  $nsid,
  "coordinates",
  l.object({ x: l.integer(), y: l.integer(), z: l.integer() }),
);

export { coordinates };

type Exit = {
  $type?: "com.cacheblasters.fm.world.room#exit";
  direction:
    | "north"
    | "south"
    | "east"
    | "west"
    | "up"
    | "down"
    | "northeast"
    | "northwest"
    | "southeast"
    | "southwest"
    | l.UnknownString;
  target: string;
  portal?: boolean;
  requiredLevel?: number;
  description?: string;
};

export type { Exit };

const exit = l.typedObject<Exit>(
  $nsid,
  "exit",
  l.object({
    direction: l.string<{
      knownValues: [
        "north",
        "south",
        "east",
        "west",
        "up",
        "down",
        "northeast",
        "northwest",
        "southeast",
        "southwest",
      ];
    }>(),
    target: l.string(),
    portal: l.optional(l.boolean()),
    requiredLevel: l.optional(l.integer()),
    description: l.optional(l.string({ maxLength: 512 })),
  }),
);

export { exit };
