/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.cacheblasters.fm.world.server'

export { $nsid }

/** Dungeon server metadata */
type Main = {
  $type: 'com.cacheblasters.fm.world.server'
  name: string
  description: string
  endpoint: l.UriString
  xrpcEndpoint?: l.UriString
  minLevel?: number
  maxLevel?: number
  theme?: string
  maxPlayers?: number
  createdAt: l.DatetimeString
}

export type { Main }

/** Dungeon server metadata */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    name: l.string({ maxLength: 128 }),
    description: l.string({ maxLength: 4096 }),
    endpoint: l.string({ format: 'uri' }),
    xrpcEndpoint: l.optional(l.string({ format: 'uri' })),
    minLevel: l.optional(l.integer({ minimum: 1 })),
    maxLevel: l.optional(l.integer({ minimum: 1 })),
    theme: l.optional(l.string({ maxLength: 256 })),
    maxPlayers: l.optional(l.integer()),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
