/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.cacheblasters.fm.action.createCharacter'

export { $nsid }

/** Create a new character on this server */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    name: l.string({ maxLength: 64 }),
    classId: l.string(),
    raceId: l.string(),
  }),
  l.jsonPayload({
    sessionId: l.string(),
    websocketUrl: l.string({ format: 'uri' }),
    spawnRoom: l.string(),
    characterState: l.optional(l.lexMap()),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
