/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.chat.locatePlayer";

export { $nsid };

/** Check if a player is currently online on this server */
const main = l.query(
  $nsid,
  l.params({ name: l.string({ maxLength: 64 }) }),
  l.jsonPayload({
    found: l.boolean(),
    playerDid: l.optional(l.string({ format: "did" })),
  }),
);
export { main };

export type $Params = l.InferMethodParams<typeof main>;
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>;
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<typeof main, B>;

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output;
