/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.chat.message";

export { $nsid };

/** Offline chat message stored in server PDS for delivery when recipient logs in */
type Main = {
  $type: "com.cacheblasters.fm.chat.message";

  /**
   * DID of the sending player
   */
  senderDid: l.DidString;

  /**
   * Character name of the sender
   */
  senderName: string;

  /**
   * DID of the recipient player
   */
  recipientDid: l.DidString;

  /**
   * The chat message content
   */
  message: string;

  /**
   * DID of the server where the message was sent from
   */
  sourceServer: l.DidString;
  createdAt: l.DatetimeString;
};

export type { Main };

/** Offline chat message stored in server PDS for delivery when recipient logs in */
const main = l.record<"tid", Main>(
  "tid",
  $nsid,
  l.object({
    senderDid: l.string({ format: "did" }),
    senderName: l.string({ maxLength: 64 }),
    recipientDid: l.string({ format: "did" }),
    message: l.string({ maxLength: 2000 }),
    sourceServer: l.string({ format: "did" }),
    createdAt: l.string({ format: "datetime" }),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
