/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.fm.chat.relay";

export { $nsid };

/** Relay a chat message to a player on this server from another federated server */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    senderName: l.string({ maxLength: 64 }),
    senderDid: l.string({ format: "did" }),
    recipientName: l.string({ maxLength: 64 }),
    message: l.string({ maxLength: 2000 }),
    sourceServer: l.string({ format: "did" }),
  }),
  l.jsonPayload({ delivered: l.boolean(), reason: l.optional(l.string()) }),
);
export { main };

export type $Params = l.InferMethodParams<typeof main>;
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>;
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<typeof main, B>;
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>;
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<typeof main, B>;

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output;
